name: checkin_rubv2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  mysql1: ^0.20.0 

  cupertino_icons: ^1.0.2
  geolocator: ^10.0.1
  shared_preferences: ^2.2.0
  http: ^1.1.0
  lottie: ^2.4.0
  camera: ^0.10.5+2
  image_picker: ^1.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.0.8
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  flutter_dotenv: ^5.1.0
  flutter_datetime_picker: ^1.5.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  provider: ^6.0.5
  flutter_line_sdk: ^2.3.3
  url_launcher: ^6.0.9
  webview_flutter: ^4.2.4
  dio: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  firebase_analytics: ^10.5.0
  clipboard: ^0.1.3
  get: ^4.6.6
  quickalert: ^1.0.2
  slide_digital_clock: 
    path: ./slide_digital_clock-1.0.3
  ntp: ^2.0.0
  connectivity: ^3.0.6
  custom_date_range_picker: ^1.0.10
  
  
flutter_icons:
    android: true
    ios: true
    image_path: "assets/HR.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/HR_ANDROID.png"
    remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env